Repository NUS-Project-SaBai/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#25 Created README in update-readme branch
  README.md
Labels: documentation

#26 Keithxun/enhancement
  api/migrations/0008_alter_vitals_diastolic_alter_vitals_heart_rate_and_more.py
  api/migrations/0009_alter_vitals_diastolic_alter_vitals_heart_rate_and_more.py
  api/models/vitals_modal.py
Labels: enhancement

#30 Auth0
  .env.example
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  api/migrations/0001_initial.py
  api/migrations/0002_remove_medication_reserve_quantity.py
  api/migrations/0003_remove_patient_picture.py
  api/migrations/0004_alter_patient_date_of_birth.py
  api/migrations/0005_patient_picture.py
  api/migrations/0006_remove_medication_remarks_alter_consult_visit_and_more.py
  api/migrations/0007_alter_vitals_blood_glucose_and_more.py
  api/migrations/0008_alter_vitals_diastolic_alter_vitals_heart_rate_and_more.py
  api/migrations/0009_alter_vitals_diastolic_alter_vitals_heart_rate_and_more.py
  api/models/__init__.py
  api/models/consult_model.py
  api/models/jwks_model.py
  api/models/patient_model.py
  api/models/user_model.py
  api/serializers/consult_serializer.py
  api/serializers/user_serializer.py
  api/tests/test_consult.py
  api/tests/test_diagnosis.py
  api/tests/test_setup.py
  api/views/consult_view.py
  api/views/patient_view.py
  requirements.txt
  sabaibiometrics/custom_exception_handler.py
  sabaibiometrics/management/commands/set_auth0_users.py
  sabaibiometrics/settings.py
  sabaibiometrics/utils.py
Labels: bug, enhancement
